/* 
/ check_sphynx_DSF.c
/
/ Test cases for Excel off-by-one rows and columns generated by 
/ some versions of "ssconvert", a tool of Gnumeric
/
/ version  2.1, 2023 September 14
/
/ Author: Sandro Furieri a.furieri@lqt.it
/
/ Disclaimer: the critical XLS testcase was kindly contributed by 
/ Swyter <swyterzone@gmail.com>
/ MS Excel 97/2000/XP y 5.0/95
/
/ ------------------------------------------------------------------------------
/ 
/ Version: MPL 1.1/GPL 2.0/LGPL 2.1
/ 
/ The contents of this file are subject to the Mozilla Public License Version
/ 1.1 (the "License"); you may not use this file except in compliance with
/ the License. You may obtain a copy of the License at
/ http://www.mozilla.org/MPL/
/ 
/ Software distributed under the License is distributed on an "AS IS" basis,
/ WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
/ for the specific language governing rights and limitations under the
/ License.
/
/ The Original Code is the FreeXL library
/
/ The Initial Developer of the Original Code is Alessandro Furieri
/ 
/ Portions created by the Initial Developer are Copyright (C) 2023
/ the Initial Developer. All Rights Reserved.
/ 
/ Contributor(s):
/
/ Alternatively, the contents of this file may be used under the terms of
/ either the GNU General Public License Version 2 or later (the "GPL"), or
/ the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
/ in which case the provisions of the GPL or the LGPL are applicable instead
/ of those above. If you wish to allow use of your version of this file only
/ under the terms of either the GPL or the LGPL, and not to allow others to
/ use your version of this file under the terms of the MPL, indicate your
/ decision by deleting the provisions above and replace them with the notice
/ and other provisions required by the GPL or the LGPL. If you do not delete
/ the provisions above, a recipient may use your version of this file under
/ the terms of any one of the MPL, the GPL or the LGPL.
/ 
*/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "freexl.h"

int
main (int argc, char *argv[])
{
    const void *handle;
    int ret;
    unsigned int info;
    const char *worksheet_name;
    unsigned short active_idx;
    unsigned int num_rows;
    unsigned short num_columns;
    FreeXL_CellValue cell_value;

    ret = freexl_open ("testdata/SphinxTextTinyTestCaseDSF.xls", &handle);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "OPEN ERROR: %d\n", ret);
	  return -1;
      }

    ret = freexl_get_info (handle, FREEXL_CFBF_VERSION, &info);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "GET_INFO ERROR for CFBF version: %d\n", ret);
	  return -2;
      }
    if (info != FREEXL_BIFF_VER_3)
      {
	  fprintf (stderr, "Unexpected CFBF_VERSION: %d\n", info);
	  return -3;
      }
      
    /* We only have one worksheet, zero index */
    ret = freexl_get_worksheet_name (handle, 0, &worksheet_name);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "Error getting worksheet name: %d\n", ret);
	  return -20;
      }
    if (strcmp (worksheet_name, "SphinxTextImported.csv") != 0)
      {
	  fprintf (stderr, "Unexpected worksheet name: %s\n", worksheet_name);
	  return -21;
      }

    ret = freexl_select_active_worksheet (handle, 0);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "Error setting active worksheet: %d\n", ret);
	  return -22;
      }

    ret = freexl_get_active_worksheet (handle, &active_idx);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "Error getting active worksheet: %d\n", ret);
	  return -23;
      }
    if (active_idx != 0)
      {
	  fprintf (stderr, "Unexpected active sheet: %d\n", active_idx);
	  return -24;
      }

    ret = freexl_worksheet_dimensions (handle, &num_rows, &num_columns);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "Error getting worksheet dimensions: %d\n", ret);
	  return -25;
      }
    if ((num_rows != 6) || (num_columns != 81))
      {
	  fprintf (stderr, "Unexpected active sheet dimensions: %u x %u\n",
		   num_rows, num_columns);
	  return -26;
      }
      
    ret = freexl_get_cell_value (handle, 5, 3, &cell_value);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "Error getting cell value (5,3): %d\n", ret);
	  return -27;
      }
    if (cell_value.type != FREEXL_CELL_TEXT)
      {
	  fprintf (stderr, "Unexpected cell (5,3) type: %u\n", cell_value.type);
	  return -28;
      }
    if (strcmp (cell_value.value.text_value, "HT_Text_NeedSaltCrystal") != 0)
      {
	  fprintf (stderr, "Unexpected cell (5,3) value: %s\n",
		   cell_value.value.text_value);
	  return -29;
      }
      
    ret = freexl_get_cell_value (handle, 2, 79, &cell_value);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "Error getting cell value (2,79): %d\n", ret);
	  return -30;
      }
    if (cell_value.type != FREEXL_CELL_TEXT)
      {
	  fprintf (stderr, "Unexpected cell (2,79) type: %u\n", cell_value.type);
	  return -31;
      }
    if (strcmp (cell_value.value.text_value, "MARKER_SOUND_END") != 0)
      {
	  fprintf (stderr, "Unexpected cell (2,79) value: %s\n",
		   cell_value.value.text_value);
	  return -32;
      }


    ret = freexl_close (handle);
    if (ret != FREEXL_OK)
      {
	  fprintf (stderr, "CLOSE ERROR: %d\n", ret);
	  return -51;
      }

    if (argc > 1 || argv[0] == NULL)
	argc = 1;		/* silencing stupid compiler warnings */

    return 0;
}
